### ISSUE TITLE
Please make an 8.0 branch

### ISSUE THREAD

**Issue by StefanRijnhart** [akretion/openerp-stock-delivery-times#4]
Hi,

we did some work on 8.0 for these modules. Can you create an 8.0 branch for our PR please?

Thanks,
Stefan.

**Comment by bguillot** [comment]
Hello Stefan, 

The 8.0 branch is ready for your PR's !

Thank you.

Benoît

**Comment by StefanRijnhart** [comment]
Grand, thanks!
